name: CI

on:
  pull_request:
  push:
    branches: [ master ]
  schedule:
    - cron:  '30 5 1,15 * *'

jobs:
  run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.2'
        minimum_versions: [false]
        coverage: ['none']
        include:
          - description: 'Minimum version'
            php: '7.4'
            minimum_versions: true
          - description: 'Log Code Coverage'
            php: '8.2'
            coverage: 'xdebug'

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-
      - name: Install dependencies
        run: composer install
        if: matrix.minimum_versions == false
      - name: Install dependencies lower
        run: composer update --no-interaction --prefer-lowest
        if: matrix.minimum_versions == true
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        if: matrix.coverage == 'none'
      - name: PHPUnit tests and Log Code coverage
        run: vendor/bin/phpunit --exclude-group proxy --coverage-clover=coverage.xml
        if: matrix.coverage == 'xdebug'
      - name: Run codecov
        uses: codecov/codecov-action@v3
        if: matrix.coverage == 'xdebug'
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
